repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: main
    hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: main
    hooks:
    - id: black

#   - repo: https://github.com/regebro/pyroma
#     rev: "4.2"
#     hooks:
#     - id: pyroma

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: main
    hooks:
    - id: ruff

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev:  main
    hooks:
    - id: mypy